Modified checks for libtool/glibtool (Mac OS X)

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -5,17 +5,22 @@
 #
 # Step 1 - check if the necessary tools appear to be there.
 #          Ideally we should check versions too, which we don't...
-if ! autoconf --version | grep GNU >/dev/null 2>&1; then
+
+if ! autoconf --version 2>&1 | grep GNU >/dev/null 2>&1; then
     echo "Cannot find GNU autoconf! Exiting..."
     exit 0
 fi
-if ! automake --version | grep GNU >/dev/null 2>&1; then
+if ! automake --version 2>&1 | grep GNU >/dev/null 2>&1; then
     echo "Cannot find GNU automake! Exiting..."
     exit 0
 fi
-if ! libtool --version | grep GNU >/dev/null 2>&1; then
-    echo "Cannot find GNU libtool! Exiting..."
-    exit 0
+
+if ! libtool --version 2>&1 | grep GNU >/dev/null 2>&1; then
+# on Mac OS X the GNU version is called glibtool...
+    if ! glibtool --version 2>&1 | grep GNU >/dev/null 2>&1; then
+        echo "Cannot find GNU libtool! Exiting..."
+        exit 0
+    fi
 fi
 
 aclocal
