Catch more errors in docs builds.
* Expand the matching of a regular expression.
* For the pipelines ending in `|| true`, commands could fail without
  triggering the conditional because empty or missing files were
  treated equivalently.

diff --git a/admin/gitlab-ci/documentation.gitlab-ci.yml b/admin/gitlab-ci/documentation.gitlab-ci.yml
--- a/admin/gitlab-ci/documentation.gitlab-ci.yml
+++ b/admin/gitlab-ci/documentation.gitlab-ci.yml
@@ -261,12 +261,27 @@ docs:build:
     - grep -i "error" docs/sphinx-*.log > sphinxDiagnostics.log || true
     - grep -i "warning" docs/sphinx-*.log >> sphinxDiagnostics.log || true
     - grep -e "error:" -e "warning:" webpage.log > doxygenErrors.log || true
-    - grep -e "ERROR:" -e "WARNING:" -e 'exception:' webpage.log > sphinxErrors.log || true
+    - grep -e "ERROR:" -e "WARNING:" -e '[Ee]xception' webpage.log | grep -v "is not documented" | grep -v "exceptions.h" > sphinxErrors.log || true
 # TODO(#4543): Resolve various warnings and errors from doxygen and its supporting tools.
 #    - if [ -s doxygenErrors.log ] ; then echo "Found errors during doxygen build"; cat doxygenErrors.log; exit 1; fi
-    - if [ -s pythonErrors.log ] ; then echo "Found Python Errors during manual build"; cat pythonErrors.log; exit 1; fi
-    - if [ -s sphinxErrors.log ] ; then echo "Found errors during Sphinx documentation build"; cat sphinxErrors.log; exit 1; fi
-    - if [ -s sphinxDiagnostics.log ] ; then echo "Found diagnostic warnings during Sphinx documentation build"; cat sphinxDiagnostics.log; exit 1; fi
+    - |
+      if [ ! -f pythonErrors.log -o -s pythonErrors.log ] ; then
+        echo "Found Python Errors during manual build"
+        cat pythonErrors.log
+        exit 1
+      fi
+    - |
+      if [ ! -f sphinxErrors.log -o -s sphinxErrors.log ] ; then
+        echo "Found errors during Sphinx documentation build";
+        cat sphinxErrors.log
+        exit 1
+      fi
+    - |
+      if [ ! -f sphinxDiagnostics.log -o -s sphinxDiagnostics.log ] ; then
+        echo "Found diagnostic warnings during Sphinx documentation build"
+        cat sphinxDiagnostics.log
+        exit 1
+      fi
     - cd ..
   artifacts:
     name: docs-artifacts-$CI_COMMIT_REF_SLUG
